### ISSUE TITLE
Doesn't work with the current version of Pretzel since .net versions are different

### ISSUE THREAD

**Issue by laedit** [k94ll13nn3/Pretzel.Categories#2]
Thanks a lot for your plugins, it is a great work! :smiley: 

But when I was trying to use this one with the current v0.4.0 of Pretzel the Tags wasn't generated.
I found that the dll is in .net 4.5.2 but Pretzel is in .net 4.5, so the plugin dll is not loaded by MEF.

Could you change the target framework to .net 4.5?

Thanks.

**Comment by k94ll13nn3** [comment]
Fixed in [1.2.0](https://github.com/k94ll13nn3/Pretzel.Categories/releases/tag/1.2.0).

**Comment by laedit** [comment]
Thanks, you are awesome!

**Comment by k94ll13nn3** [comment]
Thanks ! 

For my personnal knowledge, do you know why it didn't work with 4.5.2 on your side ? Because on my machine, I didn't have this problem.

**Comment by laedit** [comment]
Well, frankly I don't understand: I just try with the 1.2.0 version and it still doesn't work. But if I compile the source code on my computer it works perfectly.
So, I am sorry this wasn't the targeted framework as I assumed.

I will look into this and let you know if I found something.

**Comment by k94ll13nn3** [comment]
Did you unblock the file after downloading it ?

**Comment by laedit** [comment]
Ok, that was it...
Since I haven't got an error during the load I put it aside.

I am truly sorry for the disturbance.
